package com.walshe.multitenant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUserAllPropertiesEquals(BusinessUser expected, BusinessUser actual) {
        assertBusinessUserAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUserAllUpdatablePropertiesEquals(BusinessUser expected, BusinessUser actual) {
        assertBusinessUserUpdatableFieldsEquals(expected, actual);
        assertBusinessUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUserAutoGeneratedPropertiesEquals(BusinessUser expected, BusinessUser actual) {
        assertThat(actual)
            .as("Verify BusinessUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUserUpdatableFieldsEquals(BusinessUser expected, BusinessUser actual) {
        assertThat(actual)
            .as("Verify BusinessUser relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUserUpdatableRelationshipsEquals(BusinessUser expected, BusinessUser actual) {
        assertThat(actual)
            .as("Verify BusinessUser relationships")
            .satisfies(a -> assertThat(a.getBusiness()).as("check business").isEqualTo(expected.getBusiness()));
    }
}
