package com.walshe.multitenant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessInvitationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessInvitationAllPropertiesEquals(BusinessInvitation expected, BusinessInvitation actual) {
        assertBusinessInvitationAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessInvitationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessInvitationAllUpdatablePropertiesEquals(BusinessInvitation expected, BusinessInvitation actual) {
        assertBusinessInvitationUpdatableFieldsEquals(expected, actual);
        assertBusinessInvitationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessInvitationAutoGeneratedPropertiesEquals(BusinessInvitation expected, BusinessInvitation actual) {
        assertThat(actual)
            .as("Verify BusinessInvitation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessInvitationUpdatableFieldsEquals(BusinessInvitation expected, BusinessInvitation actual) {
        assertThat(actual)
            .as("Verify BusinessInvitation relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getInvitedEmail()).as("check invitedEmail").isEqualTo(expected.getInvitedEmail()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessInvitationUpdatableRelationshipsEquals(BusinessInvitation expected, BusinessInvitation actual) {
        assertThat(actual)
            .as("Verify BusinessInvitation relationships")
            .satisfies(a -> assertThat(a.getBusiness()).as("check business").isEqualTo(expected.getBusiness()));
    }
}
