package com.walshe.multitenant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAllPropertiesEquals(Business expected, Business actual) {
        assertBusinessAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAllUpdatablePropertiesEquals(Business expected, Business actual) {
        assertBusinessUpdatableFieldsEquals(expected, actual);
        assertBusinessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessAutoGeneratedPropertiesEquals(Business expected, Business actual) {
        assertThat(actual)
            .as("Verify Business auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUpdatableFieldsEquals(Business expected, Business actual) {
        assertThat(actual)
            .as("Verify Business relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUpdatableRelationshipsEquals(Business expected, Business actual) {
        // empty method
    }
}
